---
- name: Port State Event from Arista

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: podman-rippley.demoredhat.com
       port: 9092
       topic: network

  rules:
   - name: Port is down
     condition: event.body.fields.admin_status == "DOWN"
     action:
       run_job_template:
        organization: "Default"
        name: "Desired port status"

   - name: Port to be configured
     condition: event.body.name == "ceos2" and event.body.fields.admin_status == "UP"
     action:
       run_job_template:
        organization: "Default"
        name: "New port configuration"

   - name: BGP change detected
     condition: event.body.fields.session_state == "IDLE"
     action:
       run_job_template:
        organization: "Default"
        name: "BGP Troubleshooting"
        post_events: true

   - name: Trouble shoooting finished
     condition: event.status == "done"
     action:
       run_job_template:
        organization: "Default"
        name: "BGP Notify"
